name: Nodejs Automation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository and Setup Github
        uses: actions/checkout@v3
      - name: Nodejs Install
        uses: actions/setup-node@v3
      - name: Install Node Modules
        run: npm install
      - name: Format the code
        run: npm run format
