name: Nodejs Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
     - name: Clone repository and Setup Github
       uses: actions/checkout@v3
     - name: Nodjs Install
       uses: actions/setup-node@v3
    
